server:
  port: 8082
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: videoweb
    username: root
    password: admin

minio:
  endpoint: http://120.26.137.2:9000
  access-key: root
  secret-key: nhb2438012195
  bucket-name: public

redis:
  host: 120.26.137.2
  port: 6379
  password: nhb2438012195
rabbitmq:
    host: 120.26.137.2
    port: 5672
    username: guest
    password: guest
